services:
  - type: web
    name: multiwa-arabic
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && ./node_modules/.bin/prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
